# Generated by Django 4.1.7 on 2023-02-14 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('date_created', models.DateField(auto_now=True)),
                ('level', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('experience', models.PositiveIntegerField()),
            ],
        ),
    ]
