# Generated by Django 4.1.7 on 2023-02-15 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='blankuser.png', upload_to='images'),
        ),
    ]
