# Generated by Django 4.1.7 on 2023-02-18 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employment',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
