# Generated by Django 4.1.7 on 2023-03-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_employment_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='is_approved',
            field=models.IntegerField(default=0),
        ),
    ]
