# Generated by Django 4.1.7 on 2023-03-01 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_connection_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
